name: Build & Check
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check:
    name: Run Gradle checks
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      - name: Run checks
        run: ./gradlew clean check --rerun-tasks

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport

      - name: Archive code coverage results
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: server/build/reports/jacoco/test/html/

      - name: Jacoco Report to PR
        id: jacoco
        if: github.ref != 'refs/heads/main'
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/**/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
          title: '# :clipboard: Coverage Report'
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      - name: Run checks
        run: ./gradlew clean integrationTest --rerun-tasks -Dbenchmark.requests.total=10000